### ISSUE TITLE
[Feature Request] Compact version of player

### ISSUE THREAD

**Issue by prionkor** [Werter12/material-ui-audio-player#10]
First of all thank you for this wonderful project :)

I am using the player inside the table and the icons and paddings are too large at the moment. If there is a compact version of the player that would be wonderful!

![Imgur](https://i.imgur.com/6lUBaeC.png)

**Comment by Werter12** [comment]
I think you can make a player compact by removing unnecessary icons. Are they important for your app? I will try to make icons and other elements smaller using existing functionality. I hope it will be enough to make such customization.

**Comment by abeluck** [comment]
Is it currently possible to remove icons? It doesn't seem so.
 
I tried something like this:

```
    const useStyles = makeStyles((theme) => {
        return {
            volumeIcon: {
                display: "none"
            }
        }
    })
```

And the icon was hidden, but there was a whitespace gap where it belonged. And mousing over this gap revealed the volume slider.

**Comment by Werter12** [comment]
@abeluck Yes, because the styles were actually applied for the `volumeIcon` while wrapper div remained, that's why you saw volume slider hovering white space. I've added `volume` prop boolean in the `1.5.1` release to hide/display this icon-button.

**Comment by zoosm3** [comment]
Hi, I'm facing the similar issue in #213. 

> I've added volume prop boolean in the 1.5.1 release to hide/display this icon-button.

It would be nicer to add `silder` props and `progressTime` props to more simplify.

**Comment by Werter12** [comment]
Added `displaySlider` prop in the v1.6.0 release.
