### ISSUE TITLE
TypeError: Cannot read property 'duration' of null

### ISSUE THREAD

**Issue by Sandeep0695** [Werter12/material-ui-audio-player#104]
I am getting "TypeError: Cannot read property 'duration' of null' " issue while playing MP3.

The issue found at.
 function changeAudioVolume(dispatch, player) {
  61 |     return function (value) {
  62 |         if (player.current) {
  63 |             player.current.volume = value > 0 ? value / 100 : 0;
  64 |             if (player.current.muted) {
..............

Please check and solve this issue.

**Comment by Werter12** [comment]
@Sandeep0695 thanks for raising the issue! Please check 1.3.3 release I've added checks for progress, currentTime, duration.

**Comment by Sandeep0695** [comment]
Thanks a lot @Werter12 .
