### ISSUE TITLE
Feature request , play callbacks

### ISSUE THREAD

**Issue by sm2017** [Werter12/material-ui-audio-player#105]
@Werter12 I need some props like `onPlayed` , `onPaused`, `onStopped`, `onFinished`

Currently  `onPlayed` is my priority , Can you please implement it?

**Comment by Werter12** [comment]
@sm2017 I've added `onPlayed`, `onPaused`, `onFinished` props. The docs is updated. Also you could check these events in github pages `AudioPlayer Interactive` story, the callback will be triggered and text in the console.
1.3.0 version

**Comment by sm2017** [comment]
@Werter12 WOW!! thanks a lot
