### ISSUE TITLE
Removing border

### ISSUE THREAD

**Issue by jcvegan** [Werter12/material-ui-audio-player#116]
Is it possible to remove the border of the control?

Maybe by prop or any configuration settings probably?

**Comment by Werter12** [comment]
@jcvegan Hi! Which border do you mean? If you mean the border for the player. We have already prop for that - `elevation`. This actually not border but box-shadow which configurable due to the mentioned prop. Just assign 0 to it and the border will disappear.

**Comment by jcvegan** [comment]
Found it, just changing the elevation to 0 removes the border.

Thanks for your response.
