### ISSUE TITLE
player.current is null

### ISSUE THREAD

**Issue by prionkor** [Werter12/material-ui-audio-player#13]
Could you check for null in the code? I am trying to use this audio player and it breaking the code with `player.current` is null error.

```
        dispatch({ type: PLAYER_VOLUME_STATUS_UNMUTE });
  50 |     };
> 51 | }
  52 | function changeAudioVolume(dispatch, player) {
  53 |     return function (value) {
  54 |         player.current.volume = value > 0 ? value / 100 : 0;
```

**Comment by Werter12** [comment]
Thanks for rasing issue @prionkor ! I've made a fix for this. Check out v1.1.8 release.
