### ISSUE TITLE
[question]TypeError: Cannot read property 'currentTime' of null

### ISSUE THREAD

**Issue by yoonseongcoco** [Werter12/material-ui-audio-player#151]
hi thanks to your good code
i have error when close modal have audio component  while audio playing
 or i change another url page from page have audio component while audio playing
but after pause then it hasnt error

error is
TypeError: Cannot read property 'currentTime' of null
(anonymous function)
src/components/state/actions.ts:73
  70 |     };
  71 | }
  72 | function setPlayerDuration(dispatch, player) {
> 73 |     return function () {
  74 |         dispatch({ type: PLAYER_SET_DURATION, duration: player.current.duration });
  75 |     };
  76 | }
View compiled
HTMLAudioElement.handlePlayerTimeUpdate
src/components/AudioPlayer.tsx:253
  250 | React.createElement(Grid_1.default, { item: true, className: classes.commonContainer },
  251 |     React.createElement(AudioPlayControl_1.default, { classNames: classNames, icons: icons, playerStatus: state.player.status, playerColors: playerColors, replayAudio: _replayAudio, pauseAudio: _pauseAudio, playAudio: _playAudio })),
  252 | download && (React.createElement(AudioDownloadsControl_1.default, { src: src, playerColors: playerColors })),
> 253 | React.createElement(AudioVolumeControl_1.default, { muteAudio: _muteAudio, unmuteAudio: _unmuteAudio, classNames: classNames, changeAudioVolume: _changeAudioVolume, volume: state.player.volume, playerColors: playerColors }),
      | ^  254 | React.createElement(Grid_1.default, { item: true, container: true, spacing: 2, className: classnames_1.default(classes.sliderContainerWrapper) },
  255 |     (!isSingleTime || isTimePositionStart) && currentTimeComp,
  256 |     React.createElement(Grid_1.default, { item: true, className: classes.sliderContainer },

how can i do ?

**Comment by Werter12** [comment]
I couldn't reproduce your issue. I was removing a component from the page or entering a different page while audio was playing. No error showed up. But, I was able to found what piece of code could cause that error. I added check for the `currentTime` in `1.5.0` version. Please, check out that release.

**Comment by yoonseongcoco** [comment]
i checked and update to 1.5.0 but error still remain

**Comment by Werter12** [comment]
Closed due to inactivity.
