### ISSUE TITLE
with autoplay={true} the Play-Button don't switch to Pause

### ISSUE THREAD

**Issue by NiasSt90** [Werter12/material-ui-audio-player#190]
if i enable "autoplay" the play-button stays at "play" instead of switching to "pause" after rendering with an source url.

Then the first hit on the play button does nothing but now switch to pause. 
Next hit will pause the playing correctly.

**Comment by Werter12** [comment]
Hey, @NiasSt90! Thanks for writing the issue. That issue reproducing for me as well. Please check the new release `v1.5.3`. I think I fixed it.
