### ISSUE TITLE
[bug] Need to press play button twice on iOS mobile browser

### ISSUE THREAD

**Issue by Lazarencjusz** [Werter12/material-ui-audio-player#197]
I don't know why, but on iOS mobile browsers (Safari, Opera, Chrome - iOS) the component can't load and play the track on 1st play-button press. I need to click twice (there is no error in the console). Before 1st click audio player shows 0 seconds as start and end point. Then after 1st click it shows like track is loaded with correct length values. Then I click 2nd time and audio is played. Android device works ok. See my code example:

```jsx
              <Render when={!!this.state.selectedTrack}>
                <ThemeProvider key={this.state.selectedTrack} theme={muiTheme}>
                  <AudioPlayer
                    src={find(this.state.audios, { name: this.state.selectedTrack })?.url}
                    width="100%"
                    spacing={1}
                    variation="primary"
                    order="reverse"
                    debug
                  />
                </ThemeProvider>
              </Render>
```

The `Render` shows its content on `when` property,
Url is a string to the track which is created like this: 
```ts
 onDataAvailableEvent = (event: BlobEvent) => {
    this.audioChunks.push(event.data);
  };

this.stream = await navigator.mediaDevices.getUserMedia({ audio: true });
his.mediaRecorder.addEventListener('dataavailable', this.onDataAvailableEvent);


    const audioBlob = new Blob(this.audioChunks, { type: 'audio/mp3' });
// then { url: URL.createObjectURL(audioBlob) }
```

When I create simple method to play the track:
```ts
play = () => {
    const audio = new Audio(find(this.state.audios, { name: this.state.selectedTrack })?.url);
    audio.play();
  };
```

it works instantly, means correct.

Also it works when i set `autoPlay` - track is played. But I do not want to use autoplay.

All works correct on desktop browser.

**Comment by Lazarencjusz** [comment]
Possible solution to implement: 

```ts
this.player: HTMLAudioElement = new Audio(this.props.src);
this.player.addEventListener('loadedmetadata', () => {
// this.player.duration is available here
});
this.player.load();
```

**Comment by Werter12** [comment]
Hi @Lazarencjusz ! Thanks for raising the issue. I've checked that issue and yeah it's reproducing for me. I need time to properly debug it on XCode virtual device and fix it.

**Comment by Werter12** [comment]
@Lazarencjusz thanks for opening the issue! The issue is fixed https://github.com/Werter12/material-ui-audio-player/commit/842bf13c871b7c7ed898e8cee0b3b8287c92316f
