### ISSUE TITLE
[Question] Can we display only Play or Pause button?

### ISSUE THREAD

**Issue by zoosm3** [Werter12/material-ui-audio-player#213]
Can we display only Play or Pause button as in the screen capture?

<img width="34" alt="スクリーンショット 2021-01-18 19 10 42" src="https://user-images.githubusercontent.com/7535130/104901586-ed043180-59c0-11eb-8b0e-f1fa75f70dc1.png">

I would like to get only the button, but got playing time and time slider with the following code.
Playing time and time slider are no need for our requirement.

<img width="495" alt="スクリーンショット 2021-01-18 19 11 56" src="https://user-images.githubusercontent.com/7535130/104901711-145afe80-59c1-11eb-93c8-08431799f51a.png">

```
function App() {
    const srcSet = [
        'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3'
    ];

  return (
        <AudioPlayer
            elevation={1}
            width="500px"
            variation="default"
            download={false}
            loop={false}
            debug={true}
            spacing={1}
            src={srcSet}
            volume={false}
        />
  );
}
```

Any help would be appreciated.
Thanks!

**Comment by Werter12** [comment]
Hi @zoosm3 ! Sorry, for the late response. I've added for the case you have mentioned the "displaySlider" prop. If you assigned it to `false` the slider with time won't be displayed. Please check [v1.6.0](https://github.com/Werter12/material-ui-audio-player/releases/tag/v1.6.0) release. Also, I've added an example in the storybook "Small AudioPlayer" section: https://werter12.github.io/material-ui-audio-player/?path=/story/material-ui--small-audioplayer
