### ISSUE TITLE
[Feature Request] Close Button

### ISSUE THREAD

**Issue by Iamsoto** [Werter12/material-ui-audio-player#253]
Hi! 

I love this library. I have just one feature request - a close 'x' button to terminate the audio.
Ideally to be smaller than the other icons.

Thanks!

**Comment by Werter12** [comment]
Hello!  Nice idea! I've added a close button for the component in [v1.6.0](https://github.com/Werter12/material-ui-audio-player/releases/tag/v1.6.0) release. You can check it also in the published storybook in the "Small AudioPlayer" section: https://werter12.github.io/material-ui-audio-player/?path=/story/material-ui--small-audioplayer
