### ISSUE TITLE
Volume slider not interactable

### ISSUE THREAD

**Issue by JamesMHenderson** [Werter12/material-ui-audio-player#279]
If the volume slider goes over the top of another element the volume slider does not appear above the element making it impossible to change the volume as the volume slider is removed

![image](https://user-images.githubusercontent.com/43638160/111135227-509b7d00-8574-11eb-8ce4-dffe71a6c637.png)

Is it possible allow access to the volume control container within useStyles to override the styling so that z-index can be set to ensure that it is above any other element.

**Comment by Werter12** [comment]
Hi, @JamesMHenderson ! I've made the following changes in the v1.6.2 release: - Added `zIndex: 10` by default for the VolumeSliderContainer and added className `volumeSliderContainer` and now you can assign any styles to it. Sorry, for the late response!
