### ISSUE TITLE
Change audio source 

### ISSUE THREAD

**Issue by ucin3d** [Werter12/material-ui-audio-player#404]
I need to change the audio source when opening different dialogs. Each dialog should play a unique audio file, and I am using a single audio player for all the dialogs (total of 18). 

This is how the dialogs open:

	// open dialog 1
        const handleClickOpen1 = () => {
            setOpen1(true);
        };	
	// open dialog 2
		const handleClickOpen2 = () => {
            setOpen2(true);
        };
	
Tried the following solution and it did not work:

        // placeholder audio source 
		let srcAudio = ['https://domainname/placeholder.mp3'];

        const handleClickOpen1 = () => {
            setOpen1(true);
			let srcAudio = ['https://domainname/audio-01.mp3']
       };	
		const handleClickOpen2 = () => {
            setOpen2(true);
			let srcAudio = ['https://domainname/audio-02.mp3']
       };

The console shows that 'srcAudio' has been updated but the placeholder audio file is the one that still plays for both dialogs. Not sure if this is an issue or a misunderstanding on my end on how to setup the audio sources.

**Comment by Werter12** [comment]
@ucin3d According to your code, I think you should use `useState` for `srcAudio` and the component will rerender, and the new `src` will be reasigned.  Let me know how it works.

**Comment by ucin3d** [comment]
Thanks! setState worked. Here is the breakdown of the solution. 

#1
const [audioSource, setAudioSource] = useState(null);

#2
<AudioPlayer
	...
	src={audioSource}   
	...	
/>

#3
<Dialog
	...
	onEntered={() => {                                   
		GetAudio("audio-01.mp3")
	}}
	...
>

#4
function GetAudio(e){
	...
	setAudioSource(e);  
	...	
}

**Comment by ucin3d** [comment]
Thanks! setState worked. Here is the breakdown of the solution showing only the key steps and elements. 

1 const [audioSource, setAudioSource] = useState(null);
2 <AudioPlayer src={audioSource}/>
3 <Dialog onEntered={() => {GetAudio("audio-01.mp3")}}>
4 function GetAudio(e){setAudioSource(e)}

**Comment by ucin3d** [comment]
Thanks! Using setstate worked. Here is the breakdown of the solution. 

1 - const [audioSource, setAudioSource] = useState(null);

2 - <AudioPlayer src={audioSource}/>

3 - <Dialog onEntered={() => {GetAudio("audio-01.mp3")}}>

4 - function GetAudio(e){setAudioSource(e)}

**Comment by ucin3d** [comment]
Somehow #2 above refused to show up. Here it is:
2 - <AudioPlayer src={audioSource}/>

**Comment by ucin3d** [comment]
Thanks! Using setstate worked. Here is the breakdown of the solution. 

- const [audioSource, setAudioSource] = useState(null);

- <AudioPlayer src={audioSource}/>

- <Dialog onEntered={() => {GetAudio("audio-01.mp3")}}>

- function GetAudio(e){setAudioSource(e)}

**Comment by ucin3d** [comment]
Thanks! Using setState worked. Here is the simplified breakdown of the key elements in the solution. 

```
1. const [audioSource, setAudioSource] = useState(null);

2. <AudioPlayer src={audioSource}/>

3. <Dialog onEntered={() => {GetAudio("audio-01.mp3")}}>

4. function GetAudio(e){setAudioSource(e)}
```
