### ISSUE TITLE
Audio sources

### ISSUE THREAD

**Issue by ucin3d** [Werter12/material-ui-audio-player#410]
Can we add audio sources from the local development folder (src/assets/audio) or does the player only works with sources as 'https://... "?
Any inputs will be appreciated.
Thanks

**Comment by Werter12** [comment]
@ucin3d Hi! You have to serve your static files. For example, with the help of the storybook on the current project, I was able to expose static files with the help of such param `-s public`. The whole command: `start-storybook -p 6006 -c .storybook -s public`. I've created the `public` folder and put there `music.mp3` then use it: 
```
<AudioPlayer src="music.mp3" />
```
You can configure `devServer` to serve static files if you use `webpack` https://webpack.js.org/configuration/dev-server/#devservercontentbase

**Comment by ucin3d** [comment]
Thanks, your suggestion worked! I moved the audio files to the public folder and used the following for the path:

<AudioPlayer
	...
	src={"audio.mp3"}
	...
/>
