### ISSUE TITLE
Time displayed with one digit for minutes

### ISSUE THREAD

**Issue by ucin3d** [Werter12/material-ui-audio-player#420]
This is not an issue with material-ui-audio-player but a modification I am trying to implement.

I am using short audio clips and wondering how to display the time with just one digit for the minutes instead of two, as I will not have audio files running more than 9 minutes.  

Current time is displayed as 00:00
Target display as 0:00

Thanks,

**Comment by Werter12** [comment]
@ucin3d Hello! Currently, it's impossible but you can introduce PR for this. You could pass a prop and consume it here https://github.com/Werter12/material-ui-audio-player/blob/master/src/components/state/helpers.ts#L7 and modify logic
