### ISSUE TITLE
Mute button

### ISSUE THREAD

**Issue by Trbuhozborac** [Werter12/material-ui-audio-player#434]
I would like to have control over mute button, I searched over documention and there is no porperty for controling mute button. I am using this audio player in react and i want to mute or unmute audio file depending on redux state. Thanks :)
btw i found the bug where mute icon is crosed (audio  file should be muted) but i can still hear the audio file

**Comment by Werter12** [comment]
Hey @Trbuhozborac ! Sorry for the delay. I have just deployed a fresh version of the package (1.6.7) (thanks for @sairojgg PR) and you can use the `muted` prop for controlling an audio player `mute` state and volume button. Also, you can check out this feature in the storybook https://werter12.github.io/material-ui-audio-player/ and documentation.
