### ISSUE TITLE
How to pause audio without click on pause button

### ISSUE THREAD

**Issue by sitestrokes** [Werter12/material-ui-audio-player#453]
hello,

I have listed many audio and when i click on play button audio file is playing successfully but when i click on other play button then also both audio playing concurrently...

I need to stop previous audio and play current audio .

Is that possible?

Thanks

**Comment by Werter12** [comment]
@sitestrokes Hello! In the new version of player https://github.com/Werter12/material-ui-audio-player/compare/v1.6.7...v1.7.0 I've added program access (from the higher component) to audio player HTML audio and dispatch. You can take advantage of this feature (use `getPlayer` prop). Check out the storybook demo (Controlled Audio Player section) and documentation.
