### ISSUE TITLE
No built-in functionality for moving to next track.

### ISSUE THREAD

**Issue by TM818** [Werter12/material-ui-audio-player#472]
Am I losing my mind, or am I reading the documentation correctly in that this music player supports multiple tracks (can be passed an array for src), but there's no built-in icon or ability to allow the user to move to the next track? A "next track" button? 

I'm assuming I'm wrong on that - what am I missing? 

Thank you much.

**Comment by Werter12** [comment]
@TM818 Hello! Sorry, probably documentation is a little bit misleading in that question. So, if you pass an array of tracks they will be rendered in the `source` tags https://github.com/Werter12/material-ui-audio-player/blob/master/src/components/AudioPlayer.tsx#L384 
In order, the browser could choose the most suitable one. According to compatibility
