### ISSUE TITLE
Replay without Replay icon

### ISSUE THREAD

**Issue by matsuo-iguazu** [Werter12/material-ui-audio-player#497]
Hello.
Is there a way to immediately turn to the Play icon instead of displaying the Replay icon when the audio has finished playing? 
Press it to play the same audio.
Thank you

**Comment by dannykennedy** [comment]
This is probably terrible, but I found a way around this...

```
[...]
const [finished, setFinished] = useState("false");
return (
        <AudioPlayer
          [...]
          key={finished}
          onFinished={() => {
            setFinished(`${Math.random()}`);
          }}
        />
)

```
