### ISSUE TITLE
can't change style of Reply icon directly

### ISSUE THREAD

**Issue by amirHossein-Ebrahimi** [Werter12/material-ui-audio-player#6]
Reply Icon don't have any selector
add selector to your classes list like playIcon & volumeIcon

**Comment by Werter12** [comment]
Thanks for rasing this issue @amirHossein-Ebrahimi ! 
Actually, the selector for the replay icon exists, I just forgot to add it to the docs. 
You can use `replayIcon` selector. Also pause icon selector is `pauseIcon`
I've updated docs and added these selectors to the storybook in `Audio Player custom styles`
