### ISSUE TITLE
Rerender view on src change.

### ISSUE THREAD

**Issue by Venoboy** [Werter12/material-ui-audio-player#78]
Hi.
When I change src, audio progress and state of play icon stays the same. How to reload them to default state?

**Comment by Werter12** [comment]
@Venoboy Hi! I've added to the `source` property `different song` option in the `AudioPlayer Interactive` story. Which helps to reproduce the case you mentioned. As far as I can see the progress is changed properly, yes but the play button doesn't. I've fixed this. So please use the latest version.
