### ISSUE TITLE
The duration of audio is diplayed as NaN

### ISSUE THREAD

**Issue by jcvegan** [Werter12/material-ui-audio-player#82]
When setting the url to listen to an audio. I am able to listen but the part that displays the duration of the audio is displayes as NaN:NaN.

**Comment by Werter12** [comment]
@jcvegan thanks for raising the issue! Please check 1.3.3 release I've added checks for progress, currentTime, duration.

**Comment by jcvegan** [comment]
@Werter12 this checks for progress is a property?

**Comment by Werter12** [comment]
@jcvegan no. It's inner implementation. Checks in order to not allow `NaN` to be assigned on the mentioned properties.
